version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      # based on CircleCI v2.0 project walkthrough
      # https://circleci.com/docs/2.0/project-walkthrough/
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install mypy yapf pytest-cov
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Check style
          command: |
            . venv/bin/activate
            python3 -m yapf --diff --recursive covid_scheduling tests *.py
      -run:
          name: Check typing
          command: |
            . venv/bin/activate
            mypy covid_scheduling
      - run:
          name: Run unit tests
          command: |
            mkdir test-results cov-results
            . venv/bin/activate
            python3 -m pytest -vv --junitxml=test-results/junit.xml --cov=cov_results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - codecov/upload:
          file: cov_results
